### ISSUE TITLE
Полученное значение уменьшается при каждом измерении

### ISSUE THREAD

**Issue by altJSV** [GyverLibs/GyverHX711#3]
Собственно проблема в заголовке
Имею тензодатчик на 5 кг. Подключен к hx711 по схеме из описания к библиотеке. HX711, в свою очередь, подключен к ESP32 следующим образом.
![loadcell](https://github.com/GyverLibs/GyverHX711/assets/22564907/deb89fdc-44da-4537-8e7b-30acf8fbfe2d)
На весах установлена платформа для взвешивания.
Загружаю слегка измененный скетч из примера:

```
#include <GyverHX711.h>
GyverHX711 sensor(16, 13, HX_GAIN64_A);

void setup() {
  Serial.begin(9600);
}

void loop() {
  if (sensor.available()) {
    Serial.println(sensor.read());
  }
delay(1000);
}
```

Тарирование не делал, так как важно понять вообще работает все или нет.
Получаю в консоли следующий набор значений:
```
154595
154573
154517
154490
154452
154399
154338
154321
154281
154242
154198
154172
154124
154077
```
Как видно из вывода консоли, полученное значение при каждом измерении стабильно уменьшается на различные интервалы.
Отсюда есть пара вопросов. Почему такое происходит? И как то что получилось, перевести в нормальный человеческий вид? Т.е. граммы, милиграммы, килограммы и т.д

**Comment by altJSV** [comment]
Версия библиотеки 1.2, микроконтроллер ESP32, скетч пишу в Arduino IDE 2.2.1. Ядро ESP32 2.0.14

**Comment by GyverLibs** [comment]
Видимо плывёт тензодатчик. Для перевода в вес - нужно писать свою калибровку/тарирование системы
